### PR TITLE
Update EYE_Toolbox_Overview.adoc

### PR DESCRIPTION
**Pull request by woodbe**
To resolve biometricITC/cPP-toolboxes#58

### CODE REVIEW

**Review by n-kai — CHANGES_REQUESTED** [review]
L125 should be changed to 
[cols=".^2,.^3,.^3",options="header",]

**Comment by gregott** [comment]
The Eye Toolbox inventory includes the following materials: photo paper, display screen, contacts and fake eyes.  Shouldn't the list of artefacts only include these items? If so, then display screens and fake eyes should have indefinite storage times, photo paper and contacts could be 52 weeks (subject to expiration dates on the contacts due to health considerations which may vary depending if they have been placed in an eye or not).

I am fine with the 80 / 20 split in percentages for all artefact types.

**Comment by woodbe** [comment]
@gregott so the point was made during the last call that digital artifacts are easy enough to recreate that the expectation is they would not be kept for later reuse so new ones would be created every time. So storage reuse is for physical objects, not digital ones.

My expectation for contacts though is that they would be pulled as needed (since they would need to be part of the artifact, like set onto the photo), there wouldn't be any good way to store them together (since they would need to be wet while the photo would need to be dry), and so my expectation was that contacts would be acquired as needed and used "once" (the once could be for some period of time with proper storage, but not expected for a long time)

**Comment by gregott** [comment]
OK.  That makes sense to me.  Given that, then video being digital should not have a storage life in the table.  Fake eyes, although physical, are just a  carrier for the printed iris, so it makes sense not to include them.  However, since they are in the inventory and physical objects, we should make a statement about them being treated differently.  That leaves us with photos and contacts as the only physical items that would have a shelf life.  One year seems fine to me for photos.  Single use contacts makes sense the way they are being used.

**Pull request merged**
